export const LICENSE_LIST_REQUEST = 'LICENSE_LIST_REQUEST';
export const LICENSE_LIST_SUCCESS = 'LICENSE_LIST_SUCCESS';
export const LICENSE_LIST_FAIL = 'LICENSE_LIST_FAIL';

export const LICENSE_UPDATE_REQUEST = 'LICENSE_UPDATE_REQUEST';
export const LICENSE_UPDATE_SUCCESS = 'LICENSE_UPDATE_SUCCESS';
export const LICENSE_UPDATE_FAIL = 'LICENSE_LIST_FAIL';

export const LICENSE_DELETE_REQUEST = 'LICENSE_DELETE_REQUEST';
export const LICENSE_DELETE_SUCCESS = 'LICENSE_DELETE_SUCCESS';
export const LICENSE_DELETE_FAIL = 'LICENSE_DELETE_FAIL';

export const LICENSE_INSERT_REQUEST = 'LICENSE_INSERT_REQUEST';
export const LICENSE_INSERT_SUCCESS = 'LICENSE_INSERT_SUCCESS';
export const LICENSE_INSERT_FAIL = 'LICENSE_INSERT_FAIL';